
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbstdbcwgvnxqxaeorpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNic3RkYmN3Z3ZueHF4YWVvcnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mjg2OTMsImV4cCI6MjA2NzEwNDY5M30.pTLBbkakKM9A9DTvySX6SPWdpNAROhK7dBKhIIYOoWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: "public",
  },
});

// Create an untyped client for staging schema operations using raw SQL
export const stagingSupabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: "public", // Keep as public but use raw SQL for staging access
  },
});
